databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: bundle install && rails db:migrate
    startCommand: bundle exec rails s -p 10000
    